In [ ]:
from sklearn.datasets import fetch_openml
from sklearn.impute import KNNImputer
import numpy as np
import pandas as pd

In [ ]:
houses = fetch_openml(name='house_prices', as_frame=True).frame
houses

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

# Practical Data Processing Tasks Using the House Prices Dataset

This curated set of tasks leverages the House Prices dataset from scikit-learn to practice essential data processing techniques using only numpy, pandas, and sklearn. Each task addresses specific aspects of data preprocessing while preventing data leakage through proper train-test splitting.

## Imputation Tasks
1. **Missing Value Strategies Comparison**  
   Implement 4 imputation methods (mean, median, KNN, and IterativeImputer) on the 'LotFrontage' column. Compare their effects on Ridge regression performance using cross-validation

In [ ]:
X = houses[['LotFrontage']]
X.head()

   LotFrontage
0         65.0
1         80.0
2         68.0
3         60.0
4         84.0

In [ ]:
X.fillna(X.mean())

      LotFrontage
0            65.0
1            80.0
2            68.0
3            60.0
4            84.0
...           ...
1455         62.0
1456         85.0
1457         66.0
1458         68.0
1459         75.0

[1460 rows x 1 columns]

In [ ]:
X.fillna(X.median())

      LotFrontage
0            65.0
1            80.0
2            68.0
3            60.0
4            84.0
...           ...
1455         62.0
1456         85.0
1457         66.0
1458         68.0
1459         75.0

[1460 rows x 1 columns]

In [ ]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=5)
df = X.copy()
df[['LotFrontage']] = imputer.fit_transform(df[['LotFrontage']])
df

      LotFrontage
0            65.0
1            80.0
2            68.0
3            60.0
4            84.0
...           ...
1455         62.0
1456         85.0
1457         66.0
1458         68.0
1459         75.0

[1460 rows x 1 columns]

In [ ]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

imputer = IterativeImputer()
df = X.copy()
df[['LotFrontage']] = imputer.fit_transform(df[['LotFrontage']])
df

      LotFrontage
0            65.0
1            80.0
2            68.0
3            60.0
4            84.0
...           ...
1455         62.0
1456         85.0
1457         66.0
1458         68.0
1459         75.0

[1460 rows x 1 columns]

2. **Categorical Missing Data Handling**  
   Develop a pipeline that imputes missing 'MasVnrType' values using mode imputation while preserving the relationship with 'MasVnrArea'

In [ ]:
houses[['MasVnrType', 'MasVnrArea']].groupby('MasVnrType').agg({'MasVnrArea':'mean'})

            MasVnrArea
MasVnrType
BrkCmn      247.666667
BrkFace     259.008989
None          1.094907
Stone       239.304688

## Discretization Tasks
3. **Optimal Binning Strategy Analysis**  
   Use KBinsDiscretizer to transform 'LotArea' into 5 bins using uniform, quantile, and k-means strategies. Evaluate which approach maximizes correlation with log(SalePrice).

In [ ]:
from sklearn.preprocessing import KBinsDiscretizer
kd = KBinsDiscretizer(n_bins=5, strategy='quantile', encode='ordinal')
df = houses.copy()
df['LotArea'] = kd.fit_transform(df[['LotArea']])
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,1.0,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,2.0,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,3.0,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,2.0,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,4.0,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,1.0,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,4.0,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,2.0,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,2.0,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,2.0,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [ ]:
num_df = df.select_dtypes(['int64', 'float'])
num_df['SalePrice'] = np.log(num_df['SalePrice'])
num_df.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,1,60,65.0,1.0,7,5,2003,2003,196.0,706,...,0,61,0,0,0,0,0,2,2008,12.247694
1,2,20,80.0,2.0,6,8,1976,1976,0.0,978,...,298,0,0,0,0,0,0,5,2007,12.109011
2,3,60,68.0,3.0,7,5,2001,2002,162.0,486,...,0,42,0,0,0,0,0,9,2008,12.317167
3,4,70,60.0,2.0,7,5,1915,1970,0.0,216,...,0,35,272,0,0,0,0,2,2006,11.849398
4,5,60,84.0,4.0,8,5,2000,2000,350.0,655,...,192,84,0,0,0,0,0,12,2008,12.429216

In [ ]:
num_df.corr()['LotArea']['SalePrice']

0.45749447863372683

4. **Temporal Feature Engineering**  
   Discretize 'YearBuilt' into decade-based categories and assess impact on linear model performance compared to raw numeric treatment

In [ ]:
df['YearBuilt'].unique()

array([2003, 1976, 2001, 1915, 2000, 1993, 2004, 1973, 1931, 1939, 1965,
       2005, 1962, 2006, 1960, 1929, 1970, 1967, 1958, 1930, 2002, 1968,
       2007, 1951, 1957, 1927, 1920, 1966, 1959, 1994, 1954, 1953, 1955,
       1983, 1975, 1997, 1934, 1963, 1981, 1964, 1999, 1972, 1921, 1945,
       1982, 1998, 1956, 1948, 1910, 1995, 1991, 2009, 1950, 1961, 1977,
       1985, 1979, 1885, 1919, 1990, 1969, 1935, 1988, 1971, 1952, 1936,
       1923, 1924, 1984, 1926, 1940, 1941, 1987, 1986, 2008, 1908, 1892,
       1916, 1932, 1918, 1912, 1947, 1925, 1900, 1980, 1989, 1992, 1949,
       1880, 1928, 1978, 1922, 1996, 2010, 1946, 1913, 1937, 1942, 1938,
       1974, 1893, 1914, 1906, 1890, 1898, 1904, 1882, 1875, 1911, 1917,
       1872, 1905])

In [ ]:
min_year = df['YearBuilt'].min()
max_year = df['YearBuilt'].max()

bins = np.arange((min_year//10)*10, ((max_year+1)//10)*10 + 1, 10)
labels = [f'decade of {x}' for x in bins[:-1]]

In [ ]:
df['YearBuiltEncoded'] = pd.cut(df['YearBuilt'], bins=bins, labels=labels)

In [ ]:
df['YearBuiltEncoded']

0       decade of 2000
1       decade of 1970
2       decade of 2000
3       decade of 1910
4       decade of 1990
             ...
1455    decade of 1990
1456    decade of 1970
1457    decade of 1940
1458    decade of 1940
1459    decade of 1960
Name: YearBuiltEncoded, Length: 1460, dtype: category
Categories (14, object): ['decade of 1870' < 'decade of 1880' < 'decade of 1890' < 'decade of 1900' ... 'decade of 1970' < 'decade of 1980' < 'decade of 1990' < 'decade of 2000']

## Categorical Encoding Tasks
5. **High-Cardinality Feature Handling**  
   Apply frequency encoding to 'Neighborhood' while one-hot encoding 'HouseStyle'. Compare results against full one-hot encoding in a regression model

In [ ]:
freq = df['Neighborhood'].value_counts()
df['Neighborhood_encoded'] = df['Neighborhood'].map(freq)
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,YearBuiltEncoded,Neighborhood_encoded
0,1,60,RL,65.0,1.0,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,0,2,2008,WD,Normal,208500,decade of 2000,150
1,2,20,RL,80.0,2.0,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,0,5,2007,WD,Normal,181500,decade of 1970,11
2,3,60,RL,68.0,3.0,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,0,9,2008,WD,Normal,223500,decade of 2000,150
3,4,70,RL,60.0,2.0,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,0,2,2006,WD,Abnorml,140000,decade of 1910,51
4,5,60,RL,84.0,4.0,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,0,12,2008,WD,Normal,250000,decade of 1990,41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,1.0,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,0,8,2007,WD,Normal,175000,decade of 1990,79
1456,1457,20,RL,85.0,4.0,Pave,NaN,Reg,Lvl,AllPub,...,MnPrv,NaN,0,2,2010,WD,Normal,210000,decade of 1970,73
1457,1458,70,RL,66.0,2.0,Pave,NaN,Reg,Lvl,AllPub,...,GdPrv,Shed,2500,5,2010,WD,Normal,266500,decade of 1940,51
1458,1459,20,RL,68.0,2.0,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,0,4,2010,WD,Normal,142125,decade of 1940,225
1459,1460,20,RL,75.0,2.0,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,0,6,2008,WD,Normal,147500,decade of 1960,100

In [ ]:
df = pd.get_dummies(df, columns=['HouseStyle'])
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,YearBuiltEncoded,Neighborhood_encoded,HouseStyle_1.5Fin,HouseStyle_1.5Unf,HouseStyle_1Story,HouseStyle_2.5Fin,HouseStyle_2.5Unf,HouseStyle_2Story,HouseStyle_SFoyer,HouseStyle_SLvl
0,1,60,RL,65.0,1.0,Pave,NaN,Reg,Lvl,AllPub,...,decade of 2000,150,False,False,False,False,False,True,False,False
1,2,20,RL,80.0,2.0,Pave,NaN,Reg,Lvl,AllPub,...,decade of 1970,11,False,False,True,False,False,False,False,False
2,3,60,RL,68.0,3.0,Pave,NaN,IR1,Lvl,AllPub,...,decade of 2000,150,False,False,False,False,False,True,False,False
3,4,70,RL,60.0,2.0,Pave,NaN,IR1,Lvl,AllPub,...,decade of 1910,51,False,False,False,False,False,True,False,False
4,5,60,RL,84.0,4.0,Pave,NaN,IR1,Lvl,AllPub,...,decade of 1990,41,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,1.0,Pave,NaN,Reg,Lvl,AllPub,...,decade of 1990,79,False,False,False,False,False,True,False,False
1456,1457,20,RL,85.0,4.0,Pave,NaN,Reg,Lvl,AllPub,...,decade of 1970,73,False,False,True,False,False,False,False,False
1457,1458,70,RL,66.0,2.0,Pave,NaN,Reg,Lvl,AllPub,...,decade of 1940,51,False,False,False,False,False,True,False,False
1458,1459,20,RL,68.0,2.0,Pave,NaN,Reg,Lvl,AllPub,...,decade of 1940,225,False,False,True,False,False,False,False,False
1459,1460,20,RL,75.0,2.0,Pave,NaN,Reg,Lvl,AllPub,...,decade of 1960,100,False,False,True,False,False,False,False,False

6. **Ordinal Feature Transformation**  
   Manually encode 'OverallQual' as ordinal values (1-10 scale) and compare with numeric treatment using feature importance analysis[10][16].

In [ ]:
houses.OverallQual.unique()

array([ 7,  6,  8,  5,  9,  4, 10,  3,  1,  2])

## Variable Transformation Tasks
7. **Skewness Correction**  
   Implement log, Box-Cox, and Yeo-Johnson transformations on 'GrLivArea'. Use Q-Q plots to evaluate normality improvement[6][17].

In [ ]:
np.log(df['GrLivArea'])

0       7.444249
1       7.140453
2       7.487734
3       7.448334
4       7.695303
          ...
1455    7.406711
1456    7.636752
1457    7.757906
1458    6.982863
1459    7.135687
Name: GrLivArea, Length: 1460, dtype: float64

8. **Interaction Feature Creation**  
   Generate 'TotalSF' by summing 'TotalBsmtSF' and '1stFlrSF', then test its predictive power against individual features[16].

In [ ]:
df['TotalSF'] = df['TotalBsmtSF'] + df['1stFlrSF']
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,Neighborhood_encoded,HouseStyle_1.5Fin,HouseStyle_1.5Unf,HouseStyle_1Story,HouseStyle_2.5Fin,HouseStyle_2.5Unf,HouseStyle_2Story,HouseStyle_SFoyer,HouseStyle_SLvl,TotalSF
0,1,60,RL,65.0,1.0,Pave,NaN,Reg,Lvl,AllPub,...,150,False,False,False,False,False,True,False,False,1712
1,2,20,RL,80.0,2.0,Pave,NaN,Reg,Lvl,AllPub,...,11,False,False,True,False,False,False,False,False,2524
2,3,60,RL,68.0,3.0,Pave,NaN,IR1,Lvl,AllPub,...,150,False,False,False,False,False,True,False,False,1840
3,4,70,RL,60.0,2.0,Pave,NaN,IR1,Lvl,AllPub,...,51,False,False,False,False,False,True,False,False,1717
4,5,60,RL,84.0,4.0,Pave,NaN,IR1,Lvl,AllPub,...,41,False,False,False,False,False,True,False,False,2290

## Scaling Tasks
9. **Scaler Comparison**  
   Apply StandardScaler, RobustScaler, and QuantileTransformer to numeric features. Evaluate their impact on KMeans clustering silhouette scores[6][17].

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import QuantileTransformer

In [ ]:
scaler = StandardScaler()
df['TotalSF'] = scaler.fit_transform(df[['TotalSF']])
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,Neighborhood_encoded,HouseStyle_1.5Fin,HouseStyle_1.5Unf,HouseStyle_1Story,HouseStyle_2.5Fin,HouseStyle_2.5Unf,HouseStyle_2Story,HouseStyle_SFoyer,HouseStyle_SLvl,TotalSF
0,1,60,RL,65.0,1.0,Pave,NaN,Reg,Lvl,AllPub,...,150,False,False,False,False,False,True,False,False,-0.645508
1,2,20,RL,80.0,2.0,Pave,NaN,Reg,Lvl,AllPub,...,11,False,False,True,False,False,False,False,False,0.386174
2,3,60,RL,68.0,3.0,Pave,NaN,IR1,Lvl,AllPub,...,150,False,False,False,False,False,True,False,False,-0.482879
3,4,70,RL,60.0,2.0,Pave,NaN,IR1,Lvl,AllPub,...,51,False,False,False,False,False,True,False,False,-0.639156
4,5,60,RL,84.0,4.0,Pave,NaN,IR1,Lvl,AllPub,...,41,False,False,False,False,False,True,False,False,0.088867
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,1.0,Pave,NaN,Reg,Lvl,AllPub,...,79,False,False,False,False,False,True,False,False,-0.399023
1456,1457,20,RL,85.0,4.0,Pave,NaN,Reg,Lvl,AllPub,...,73,False,False,True,False,False,False,False,False,1.772339
1457,1458,70,RL,66.0,2.0,Pave,NaN,Reg,Lvl,AllPub,...,51,False,False,False,False,False,True,False,False,0.152394
1458,1459,20,RL,68.0,2.0,Pave,NaN,Reg,Lvl,AllPub,...,225,False,False,True,False,False,False,False,False,-0.081386
1459,1460,20,RL,75.0,2.0,Pave,NaN,Reg,Lvl,AllPub,...,100,False,False,True,False,False,False,False,False,0.370928

10. **Target-Aware Scaling**  
    Implement PCA before and after scaling, analyzing explained variance ratios for raw vs scaled features[6][14].

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=5)
new_df = pd.DataFrame(pca.fit_transform(num_df.dropna()))
new_df

                0           1           2           3           4
0      -36.250550  207.087177 -781.198404 -740.772998 -169.952653
1       41.774944 -769.921360 -166.846109 -721.413244  -61.488026
2       54.959303  421.081640 -481.228081 -733.720476 -144.522196
3     -155.101611  539.486441 -262.359138 -727.044034   41.260780
4      673.702772  528.114818 -591.609363 -727.857853 -148.825928
...           ...         ...         ...         ...         ...
1116  -155.152499  671.823594  193.803118  725.785639 -119.634750
1117  1007.577794 -474.265280  142.383100  763.700353  509.093266
1118   554.211067  969.947013 -275.497512  795.201875   13.044414
1119  -656.655267 -390.573153  -40.398812  733.298933  639.784583
1120   -74.537609 -742.604062 -238.980597  734.761185  121.713819

[1121 rows x 5 columns]

## Missing Data Handling Tasks
11. **Missingness Pattern Analysis**  
    Use matrix visualizations to identify correlations between missing 'GarageYrBlt' and present 'GarageType' values[2][8][12].

In [ ]:
df.GarageType.shape

(1460,)

In [ ]:
num_df.corr()[['GarageYrBlt','GarageType']]

               GarageYrBlt
Id                0.000072
MSSubClass        0.085072
LotFrontage       0.070250
LotArea           0.068781
OverallQual       0.547766
OverallCond      -0.324297
YearBuilt         0.825667
YearRemodAdd      0.642277
MasVnrArea        0.252691
BsmtFinSF1        0.153484
BsmtFinSF2       -0.088011
BsmtUnfSF         0.190708
TotalBsmtSF       0.322445
1stFlrSF          0.233449
2ndFlrSF          0.070832
LowQualFinSF     -0.036363
GrLivArea         0.231197
BsmtFullBath      0.124553
BsmtHalfBath     -0.077464
FullBath          0.484557
HalfBath          0.196785
BedroomAbvGr     -0.064518
KitchenAbvGr     -0.124411
TotRmsAbvGrd      0.148112
Fireplaces        0.046822
GarageYrBlt       1.000000
GarageCars        0.588920
GarageArea        0.564567
WoodDeckSF        0.224577
OpenPorchSF       0.228425
EnclosedPorch    -0.297003
3SsnPorch         0.023544
ScreenPorch      -0.075418
PoolArea         -0.014501
MiscVal          -0.032417
MoSold            0.005337
YrSold           -0.001014
SalePrice         0.541073

12. **Advanced Imputation Validation**  
    Create synthetic missing values in 'MasVnrArea', then compare imputation accuracy of MICE vs KNN methods using known ground truth[14][18].

In [ ]:
from sklearn.impute import KNNImputer

knn = KNNImputer(n_neighbors=5)
df['MasVnrArea'] = knn.fit_transform(df[['MasVnrArea']])
df['MasVnrArea'].isnull().sum()

0

## Outlier Detection Tasks
13. **IQR-Based Filtering**  
    Identify outliers in 'GrLivArea' using 1.5*IQR rule and analyze their impact on sale price prediction error[7][18].

In [ ]:
Q1 = df['GrLivArea'].quantile(0.25)
Q3 = df['GrLivArea'].quantile(0.75)

IQR_15 = 1.5*(Q3-Q1)
outliers = df[(df['GrLivArea']< Q1 - IQR_15) | (df['GrLivArea']>Q3 + IQR_15)]
outliers

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,Neighborhood_encoded,HouseStyle_1.5Fin,HouseStyle_1.5Unf,HouseStyle_1Story,HouseStyle_2.5Fin,HouseStyle_2.5Unf,HouseStyle_2Story,HouseStyle_SFoyer,HouseStyle_SLvl,TotalSF
58,59,60,RL,66.0,4.0,Pave,NaN,IR2,HLS,AllPub,...,25,False,False,False,False,False,True,False,False,0.782584
118,119,60,RL,90.0,4.0,Pave,NaN,Reg,Lvl,AllPub,...,59,False,False,False,False,False,True,False,False,1.463597
185,186,75,RM,90.0,4.0,Pave,NaN,IR2,Lvl,AllPub,...,113,False,False,False,True,False,False,False,False,0.514499
197,198,75,RL,174.0,4.0,Pave,NaN,Reg,Lvl,AllPub,...,225,False,False,False,False,False,True,False,False,0.635201
231,232,60,RL,174.0,4.0,Pave,NaN,IR1,Lvl,AllPub,...,41,False,False,False,False,False,True,False,False,0.929968
304,305,75,RM,87.0,4.0,Pave,NaN,Reg,Lvl,AllPub,...,113,False,False,False,True,False,False,False,False,1.175183
324,325,80,RL,96.0,3.0,Pave,NaN,Reg,Lvl,AllPub,...,225,False,False,False,False,False,False,False,True,0.492900
496,497,20,RL,NaN,4.0,Pave,NaN,IR1,Lvl,AllPub,...,41,False,False,True,False,False,False,False,False,5.346383
523,524,60,RL,130.0,4.0,Pave,NaN,IR1,Bnk,AllPub,...,100,False,False,False,False,False,True,False,False,5.153260
583,584,75,RM,75.0,4.0,Pave,NaN,Reg,Lvl,AllPub,...,113,False,False,False,False,True,False,False,False,0.683482
608,609,70,RL,78.0,3.0,Pave,NaN,Reg,HLS,AllPub,...,51,False,False,False,False,False,True,False,False,0.870252
635,636,190,RH,60.0,3.0,Pave,Pave,Reg,Bnk,AllPub,...,25,False,False,False,True,False,False,False,False,0.838488
691,692,60,RL,104.0,4.0,Pave,NaN,IR1,Lvl,AllPub,...,41,False,False,False,False,False,True,False,False,3.389743
769,770,60,RL,47.0,4.0,Pave,NaN,IR2,HLS,AllPub,...,25,False,False,False,False,False,True,False,False,1.422939
798,799,60,RL,104.0,4.0,Pave,NaN,Reg,Lvl,AllPub,...,77,False,False,False,False,False,True,False,False,2.124280
803,804,60,RL,107.0,4.0,Pave,NaN,Reg,Lvl,AllPub,...,77,False,False,False,False,False,True,False,False,1.585569
961,962,60,RL,NaN,4.0,Pave,NaN,IR1,Lvl,AllPub,...,73,False,False,False,False,False,True,False,False,0.828324
1024,1025,20,RL,NaN,4.0,Pave,NaN,IR1,Lvl,AllPub,...,38,False,False,True,False,False,False,False,False,2.849761
1031,1032,75,RL,102.0,4.0,Pave,NaN,Reg,Lvl,AllPub,...,25,False,False,False,True,False,False,False,False,0.369657
1046,1047,60,RL,85.0,4.0,Pave,NaN,IR1,Lvl,AllPub,...,25,False,False,False,False,False,True,False,False,2.241170
1142,1143,60,RL,77.0,2.0,Pave,NaN,Reg,Lvl,AllPub,...,150,False,False,False,False,False,True,False,False,0.904557
1169,1170,60,RL,118.0,4.0,Pave,NaN,IR1,Lvl,AllPub,...,41,False,False,False,False,False,True,False,False,1.957839
1173,1174,50,RL,138.0,4.0,Pave,NaN,IR1,Bnk,AllPub,...,28,True,False,False,False,False,False,False,False,1.288261
1175,1176,50,RL,85.0,3.0,Pave,NaN,Reg,Lvl,AllPub,...,41,True,False,False,False,False,False,False,False,2.022637
1182,1183,60,RL,160.0,4.0,Pave,NaN,IR1,Lvl,AllPub,...,41,False,False,False,False,False,True,False,False,3.286829
1268,1269,50,RL,NaN,4.0,Pave,NaN,IR1,Lvl,AllPub,...,51,True,False,False,False,False,False,False,False,0.604708
1298,1299,60,RL,313.0,4.0,Pave,NaN,IR3,Bnk,AllPub,...,100,False,False,False,False,False,True,False,False,10.903747
1312,1313,60,RL,NaN,2.0,Pave,NaN,IR1,Lvl,AllPub,...,41,False,False,False,False,False,True,False,False,0.871523
1328,1329,50,RM,60.0,3.0,Pave,Grvl,Reg,Lvl,AllPub,...,113,True,False,False,False,False,False,False,False,1.110385
1353,1354,50,RL,56.0,4.0,Pave,NaN,IR1,Lvl,AllPub,...,41,True,False,False,False,False,False,False,False,2.370766
1386,1387,60,RL,80.0,4.0,Pave,NaN,IR1,Lvl,AllPub,...,73,False,False,False,False,False,True,False,False,0.716516

14. **Z-Score Anomaly Detection**  
    Flag homes with Z-scores >3 in 'TotalBsmtSF' and evaluate their characteristics compared to the overall population[7][12].

In [45]:
mean_bsmt = df['TotalBsmtSF'].mean(skipna=True)
std_bsmt = df['TotalBsmtSF'].std(skipna=True, ddof=1)

Z_scores = np.abs(df['TotalBsmtSF'] - mean_bsmt)/(std_bsmt)

df[Z_scores > 3]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,Neighborhood_encoded,HouseStyle_1.5Fin,HouseStyle_1.5Unf,HouseStyle_1Story,HouseStyle_2.5Fin,HouseStyle_2.5Unf,HouseStyle_2Story,HouseStyle_SFoyer,HouseStyle_SLvl,TotalSF
224,225,20,RL,103.0,4.0,Pave,NaN,Reg,Lvl,AllPub,...,77,False,False,True,False,False,False,False,False,3.257606
332,333,20,RL,85.0,3.0,Pave,NaN,IR1,Lvl,AllPub,...,77,False,False,True,False,False,False,False,False,3.322404
440,441,20,RL,105.0,4.0,Pave,NaN,Reg,Lvl,AllPub,...,77,False,False,True,False,False,False,False,False,4.162235
496,497,20,RL,NaN,4.0,Pave,NaN,IR1,Lvl,AllPub,...,41,False,False,True,False,False,False,False,False,5.346383
523,524,60,RL,130.0,4.0,Pave,NaN,IR1,Bnk,AllPub,...,100,False,False,False,False,False,True,False,False,5.153260
691,692,60,RL,104.0,4.0,Pave,NaN,IR1,Lvl,AllPub,...,41,False,False,False,False,False,True,False,False,3.389743
1044,1045,20,RL,80.0,2.0,Pave,NaN,Reg,Lvl,AllPub,...,73,False,False,True,False,False,False,False,False,3.593030
1182,1183,60,RL,160.0,4.0,Pave,NaN,IR1,Lvl,AllPub,...,41,False,False,False,False,False,True,False,False,3.286829
1298,1299,60,RL,313.0,4.0,Pave,NaN,IR3,Bnk,AllPub,...,100,False,False,False,False,False,True,False,False,10.903747
1373,1374,20,RL,NaN,3.0,Pave,NaN,Reg,Lvl,AllPub,...,41,False,False,True,False,False,False,False,False,3.870009



## Data Leakage Prevention Tasks
15. **Temporal Validation**  
    Create time-based split using 'YrSold' to prevent leakage, comparing model performance with random splits[13][18].

16. **Pipeline Integrity Test**  
    Build a full pipeline that prevents information leakage between training/testing sets for all preprocessing steps[18][19].

## Comprehensive Challenge
17. **End-to-End Optimization**  
    Develop a complete processing pipeline that maximizes Ridge regression R² score while using:  
    - IterativeImputer for numeric features  
    - Ordinal encoding for quality ratings  
    - Quantile-based scaling  
    - Outlier-aware transformation  
    Validate using nested cross-validation[1][14][16][18].

These tasks progress from foundational techniques to advanced pipeline development, each focusing on practical implementation while adhering to strict library constraints. The House Prices dataset provides sufficient complexity to reveal subtle differences between processing approaches.